services:
  client:
    image: node:20.0.0-alpine
    user: node
    entrypoint: sh -c
    working_dir: /home/node
    command: '"npm install && npm run dev"'
    ports:
      - 5173:5173
    volumes:
      - ./client:/home/node

  server:
    image: node:20.0.0-alpine
    environment:
      - MONGO_URL=mongodb://root:password@mongo:27017/app
      - POSTGRES_URL=postgres://root:password@postgres:5432/app
    user: node
    tty: true
    stdin_open: true
    working_dir: /home/node
    entrypoint: sh -c
    command: '"npm install && npm run dev"'
    ports:
      - 8000:8000
    volumes:
      - ./server:/home/node/

  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app


  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
      - ./SampleCollections:/SampleCollections
    ports:
      - 127.0.0.1:27017:27017
    working_dir: /home/node
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: app

volumes:
    postgres-data:
    mongo-data: