### GET request to the root endpoint
GET http://localhost:8000

###

### POST request to the root endpoint
POST http://localhost:8000
Content-Type: application/json

{
  "key": "value"
}

###

### GET request to the /users endpoint
###
PATCH http://localhost:8000/users/1
Content-Type: application/json

{
  "password": "Azerty1234!"
}
###
POST http://localhost:8000/users
Content-Type: application/json

{
  "email": "john@doe.fr",
  "password": "Azerty1234!"
}

### Any request to the security routes
###
POST http://localhost:8000/login
Content-Type: application/json

{
  "email": "test@example.cor",
  "password": "Testpassword1"
}

### Any request to the user routes
###
GET http://localhost:8000/users

### Get a user by id
GET localhost:8000/users/0ab12aa2-b7e3-456c-93a5-05e81a3d924b

### Get user roles
POST localhost:8000/users/role
Content-Type: application/json

{
  "role": "f120fc9e-d43c-4726-8f44-37e5531dd169"
}

### Get all roles
GET localhost:8000/role


###
GET localhost:8000/users/d7c8ce2f-9d2c-4939-b5f6-f6bc19c7cfd4

###
POST localhost:8000/user
Content-Type: application/json

{
  "email": "tesddo@ex.cop",
  "password": "Testpassword&1",
  "role": "ROLE_USER",
  "firstname":"Test",
  "lastname": "Tester",
  "phone": "0606060606"
}

###
PUT localhost:8000/users/12199d2f-d66d-467d-8fa2-690a93e7542f
Content-Type: application/json

{
  "id": "12199d2f-d66d-467d-8fa2-690a93e7542f",
  "email": "testons@example.com",
  "password": "Testpassword&1",
  "role": ["ROLE_USER"],
  "firstname":"Test",
  "lastname": "Tester",
  "phone": "0606060606",
  "deleted": false
}
###
DELETE localhost:8000/user/16b96df0-7b8e-4902-bd4f-3e1ca8313fe8

### Structure of models
GET localhost:8000/model/User

### Send mail

POST localhost:8000/email

### Create category
POST localhost:8000/category
Content-Type: application/json

{
  "name": "Clips-ins"
}

### Create product
POST localhost:8000/product
Content-Type: application/json

{
  "name": "Clips-ins",
  "description": "Description",
  "price_ttc": "10",
  "price_ht": "8",
  "slug": "clips-ins",
  "category_id": "test"
}


### Get Address by user
GET localhost:8000/address/8c9b7e53-a973-476a-a86f-18d6f7e9215f

### Create Address
POST localhost:8000/address
Content-Type: application/json

{
  "user_id": "1adac9b1-7f47-4ea2-b79e-ff01c9641991",
  "street": "1 rue de la paix",
  "postal_code": "75000",
  "city": "Paris",
  "country": "France"
}

### Update Address
PATCH localhost:8000/address/a0d6a17c-1a31-4988-a5d3-e485b2583c69
Content-Type: application/json

{
  "postal_code":"77120"
}

### Delete Address
DELETE localhost:8000/address/a0d6a17c-1a31-4988-a5d3-e485b2583c69

### Create Product
POST localhost:8000/product
Content-Type: application/json

{
  "name": "Clips-ins",
  "description": "Description",
  "price_ttc": "10",
  "price_ht": "8",
  "slug": "clips-ins",
  "category_id": "22912a9c-6bde-429e-bdbc-741beb3ac9a8"
}