name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.0.0-alpine
        uses: actions/setup-node@v3
        with:
          node-version: '20.0.0'
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  client-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.0.0-alpine
        uses: actions/setup-node@v3
        with:
          node-version: '20.0.0'
          cache: 'npm'
      - run: cd client/front && npm ci
      - run: cd client/front && npm test